language: android

jdk: oraclejdk7

branches:
  only:
    - master
    - develop

android:
  components:
    # The BuildTools version used by your project
    - build-tools-23.0.1
    # The SDK version used to compile your project
    - android-23
    # Additional components
    ## Android Support Library (appcompat)
    - extra-android-support
    ## Android Support Repository
    - extra-android-m2repository

# decrypt adventskalender.keystore
before_install:
- openssl aes-256-cbc -K $encrypted_6510f260417b_key -iv $encrypted_6510f260417b_iv -in adventskalender.keystore.enc -out adventskalender.keystore -d

script:
  - ./gradlew assembleBintray

after_script:
  - cat app/build/outputs/lint-results.html
  - ./gradlew signingReport

before_deploy:
  - cp app/build/outputs/apk/app-bintray.apk app/build/outputs/apk/adventskalender-app-$(date +%Y-%m-%d_%H-%M-%S)-$TRAVIS_BRANCH-$TRAVIS_COMMIT.apk

deploy:
  - provider: bintray
    skip_cleanup: true
    file: deploy-bintray.txt
    user: "rleh"
    key:
      secure: YJzAd3U5eFyQZQkLVPhnlUZ5qZCu8V9xVH1LOMUBKr6ggBrlg39dYkQR8Sj04rgWnnBi+fxy1v7wRBdNmaLF/8oGnG9Lsr5roDihg13CchmV/jnlT6JODGSfth0p8krf6kGVNQYDPoNFNoVgcsSoAuojIjZ4oOL8aFjsYt35WrwOFljeT0cYiuoMBzM7uDvwyoyd/mhagB9jmns7ugjp2UmUbG1LESQVenxOIiEqChZbWAOLgzZbsdLSJqRftbip2Tu8k/fqEePMTuGZtpCixl7DLztrdE1S5WY1fwxI+ksmxNFEQsI13ov+08AkPoWL4UrMQObapTLsGZW/ybo5RnpvtL/HGij0hYYuzcmoTb+t1NnIHTTD8ipvsbEPmBi3Zqwwlw5QvRAhQN2lgT5FlXz0Eczuk8/m7hnKAeFly9YUKPSKYxBgXBROFKGwqWwQ79t7Xm4RawzKaUSsSbY/9VKdtE5Q8j87nM1gk1QwwFBd8LDWXiDUSPqArs+xc5147KXug7uYOWKtrhZD/+URvdyioQ7S80LgiU7Jq6klspPoDSz9sUNsr7ewwZTvHGSUEZvIdzQ9TYOgSRy9ynPL1JqIel07uvTQgr9nXHD3n7tZzBOYrA8UBcZ6zH2DVTj0pPd7jYdFY4NlGe+7vpIqc3QG07i7ZhZvks33ELsEXeg=
    on:
      branch:
        - master
        - develop
